### ISSUE TITLE
BlenDir started saving the folder to the same location

### ISSUE THREAD

**Issue by ColoredSine** [DanielBoxer/BlenDir#1]
Hi! 
I previously created a folder on the desktop and made a startup file from this folder and now BlenDir always saves the folder on the desktop regardless of the specified location. Can I fix this without losing my settings?

**Comment by danielboxer** [comment]
Hi, what do you mean by a startup file? Like a folder structure file?

Could you show the structure that's causing problems?

**Comment by ColoredSine** [comment]
![image](https://github.com/DanielBoxer/BlenDir/assets/101879410/c0b6972c-21c0-4d84-8f5f-d1fa0e7ee4d3)

**Comment by ColoredSine** [comment]
То есть если создать структуру и оттуда сохранить startup file, то при запуске нового пустого проекта всё равно откуда-то будет браться информация о старом местонахождении файла, и BlenDir будет на том же месте создавать папку независимо от выбранного места.

**Comment by ColoredSine** [comment]
So if you create a structure and accidentally save startup file from there, then when you start a new empty project, information about the old file location will still be taken from somewhere and BlenDir will create a structure in the old place, regardless of the selected location.

**Comment by danielboxer** [comment]
Yeah, the startup file was saving some properties that shouldn't be saved.

I added a check for this that will make it work properly after saving a startup file and using the add-on on a new unsaved project. Though if you save the project before using the add-on and you run into this issue again, there's a new button in the preferences that should fix it.

Make sure to save your folder structure file somewhere before installing the new version of the add-on so you don't lose it.

**Comment by ColoredSine** [comment]
Thank you!
